### ISSUE TITLE
Add help

### ISSUE THREAD

**Issue by bronzehedwick** [daliusd/ghlite.nvim#7]
**Describe the bug**
Add Neovim help version of the documentation for local, in editor viewing.

**To Reproduce**
1. Type <kbd>:help ghlite</kbd>

**Expected behavior**
Help is available inside Neovim.

**Neovim version and OS:**
Any.

**Comment by daliusd** [comment]
OK. This surprised me. This is what I get:

![image](https://github.com/user-attachments/assets/25960627-d8d3-45e3-bb2b-033143456e74)

It is wrong location as it focus on Commands section, but otherwise it is completely readable. As well it is lazy.nvim specific I assume. I have not written any documentation and lazy.nvim somehow figured out to use README.md for documentation. So in the end I don't get error and I get something useful.

What are you using and what do you get? I am still looking if I can do better.

**Comment by bronzehedwick** [comment]
Thanks for the response @daliusd, and all your hard work making this plugin.

Here's the error I'm seeing when I type <kbd>:help ghlite</kbd>.
<img width="366" alt="Screenshot 2024-11-05 at 8 52 59 AM" src="https://github.com/user-attachments/assets/1b043570-c4c9-476a-b388-e6e19e10d870">

I looked at the local files in the plugin, and am not seeing a `doc` directory.
<img width="734" alt="Screenshot 2024-11-05 at 8 55 18 AM" src="https://github.com/user-attachments/assets/926d0c10-5055-43b4-930f-146d5707a032">

**Comment by daliusd** [comment]
I hope it is what you were expecting.

**Comment by bronzehedwick** [comment]
Perfect, thank you @daliusd!
